CREATE TABLE IF NOT EXISTS company(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(10) NOT NULL UNIQUE,
rating DECIMAL(3,2),
created_by VARCHAR(10) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);