spring.application.name=jobPortal
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:~/dummyData;AUTO_SERVER=true
#spring.sql.init.mode=always // first time run with this


spring.datasource.username=sa
spring.datasource.password=
#spring.database.driver-class.name=org.h2.Driver
#spring.h2.console.path=/h2-console
#spirng.h2.console.enabled=true
